# Generated by Django 5.0.6 on 2024-07-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0006_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_subscription_user',
            field=models.BooleanField(default=False),
        ),
    ]
